# -*- coding: utf-8 -*-
"""Prune_Net.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17dq7MTYEBF9wRZO6AM2gFau3vCf-45ju
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision
import torchvision.transforms as transforms
import torch.optim as optim
import matplotlib.pyplot as plt
import math

# --- 1. THE PRUNABLE LAYER ---
class PrunableLinear(nn.Module):
    def __init__(self, in_features, out_features):
        super().__init__()
        self.weight = nn.Parameter(torch.Tensor(out_features, in_features))
        self.bias = nn.Parameter(torch.Tensor(out_features))
        self.gate_scores = nn.Parameter(torch.Tensor(out_features, in_features))
        self.reset_parameters()

    def reset_parameters(self):
        nn.init.kaiming_uniform_(self.weight, a=math.sqrt(5))
        nn.init.zeros_(self.bias)

        nn.init.constant_(self.gate_scores, 0.5)

    def forward(self, x):
        gates = torch.sigmoid(self.gate_scores)
        pruned_weights = self.weight * gates
        return F.linear(x, pruned_weights, self.bias)

# --- 2. THE MODEL ---
class SelfPruningNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = PrunableLinear(3072, 512)
        self.fc2 = PrunableLinear(512, 10)

    def forward(self, x):
        x = x.view(-1, 3072)
        x = F.relu(self.fc1(x))
        return self.fc2(x)

# --- 3. LOSS & EXPERIMENT LOGIC ---
def get_sparsity_loss(model):
    s_loss = 0
    for m in model.modules():
        if isinstance(m, PrunableLinear):
            # Strict L1 Norm of the sigmoid gates
            s_loss += torch.sum(torch.abs(torch.sigmoid(m.gate_scores)))
    return s_loss

def run_experiment(lambda_val, trainloader, testloader, device, epochs=15):
    model = SelfPruningNet().to(device)
    # Increased learning rate to 0.002 to help parameters move faster
    optimizer = optim.Adam(model.parameters(), lr=0.002)
    criterion = nn.CrossEntropyLoss()

    for epoch in range(epochs):
        model.train()
        running_loss = 0.0
        for inputs, labels in trainloader:
            inputs, labels = inputs.to(device), labels.to(device)
            optimizer.zero_grad()
            outputs = model(inputs)

            # Loss Formulation: Classification + (Lambda * Sparsity)
            total_loss = criterion(outputs, labels) + (lambda_val * get_sparsity_loss(model))
            total_loss.backward()
            optimizer.step()
            running_loss += total_loss.item()

        
        print(f"  Epoch {epoch+1}/{epochs} | Avg Loss: {running_loss/len(trainloader):.4f}")

    # --- EVALUATION ---
    model.eval()
    correct, total, pruned, weights = 0, 0, 0, 0
    with torch.no_grad():
        for inputs, labels in testloader:
            inputs, labels = inputs.to(device), labels.to(device)
            outputs = model(inputs)
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

        for m in model.modules():
            if isinstance(m, PrunableLinear):
                gates = torch.sigmoid(m.gate_scores)
                
                pruned += torch.sum(gates < 0.01).item()    # Strict threshold restored to 0.01 as per the JD
                weights += gates.numel()

    return (100 * correct / total), (100 * pruned / weights), model

# --- 4. MAIN EXECUTION ---
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5,), (0.5,))])
trainset = torchvision.datasets.CIFAR10(root='./data', train=True, download=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=64, shuffle=True)
testset = torchvision.datasets.CIFAR10(root='./data', train=False, download=True, transform=transform)
testloader = torch.utils.data.DataLoader(testset, batch_size=64, shuffle=False)

# Adjusted Lambdas to capture the perfect trade-off curve
lambdas = [1e-5, 1e-4, 1e-3]
results = []
final_model = None

for l in lambdas:
    print(f"\n--- Running Lambda: {l} ---")
    acc, sp, model = run_experiment(l, trainloader, testloader, device, epochs=15)
    results.append((l, acc, sp))
   
    final_model = model
    print(f"Result -> Acc: {acc:.2f}%, Sparsity: {sp:.2f}%")

# --- 5. PLOTTING ---
gate_vals = []
for m in final_model.modules():
    if isinstance(m, PrunableLinear):
        gate_vals.extend(torch.sigmoid(m.gate_scores).detach().cpu().numpy().flatten())

plt.figure(figsize=(8,5))
plt.hist(gate_vals, bins=50, color='teal', alpha=0.8)
plt.title("Distribution of Final Gate Values (Lambda = 0.001)")
plt.xlabel("Gate Value (0.0 = Pruned, 1.0 = Kept Active)")
plt.ylabel("Number of Weights")
plt.grid(axis='y', alpha=0.5)
plt.show()